"""
This script is used to check if all the possible values are unique and if the ids are consecutive.
If they are not, to print them out.

"""

all_added = [               
(1  ,       'main',                             'None'),	                        
(2  ,       'main',                             'disarmed'),	                        
(3  ,       'main',                             'armed_home'),	                        
(4  ,       'main',                             'armed_away'),	                        
(5  ,       'main',                             'armed_night'),	                        
(6  ,       'main',                             'armed_vacation'),	                
(7  ,       'main',                             'armed_custom_bypass'),                 
(8  ,       'main',                             'pending'),	                        
(9  ,       'main',                             'arming'),	                        
(10 ,       'main',                             'disarming'),	                        
(11 ,       'main',                             'triggered'),                           
(12 ,       'main',                             'unknown'),	                        
(13 ,       'main',                             'unavailable'),                         
(14 ,       'code_format',                      'number'),                              
(15 ,       'code_format',                      'text'),                                
(16 ,       'changed_by',                       'string'),                              
(17 ,       'code_arm_required',                'string'),                              
(18 ,       'supported_features',               'int'),                                 
(19 ,       'at',                               'string'),                              
(20 ,       'main',                             'on'),                                  
(21 ,       'main',                             'off'),                                 
(22 ,       'device_class',                     'battery'),                             
(23 ,       'device_class',                     'battery_charging'),                    
(24 ,       'device_class',                     'co'),                                  
(25 ,       'device_class',                     'cold'),                                
(26 ,       'device_class',                     'connectivity'),                        
(27 ,       'device_class',                     'door'),                                
(28 ,       'device_class',                     'garage_door'),                         
(29 ,       'device_class',                     'gas'),                                 
(30 ,       'device_class',                     'heat'),                                
(31 ,       'device_class',                     'light'),                               
(32 ,       'device_class',                     'lock'),                                
(33 ,       'device_class',                     'moisture'),                            
(34 ,       'device_class',                     'motion'),                              
(35 ,       'device_class',                     'moving'),                              
(36 ,       'device_class',                     'occupancy'),                           
(37 ,       'device_class',                     'opening'),                             
(38 ,       'device_class',                     'plug'),                                
(39 ,       'device_class',                     'power'),                               
(40 ,       'device_class',                     'presence'),                            
(41 ,       'device_class',                     'problem'),                             
(42 ,       'device_class',                     'running'),                             
(43 ,       'device_class',                     'safety'),                              
(44 ,       'device_class',                     'smoke'),                               
(45 ,       'device_class',                     'sound'),                               
(46 ,       'device_class',                     'tamper'),                              
(47 ,       'device_class',                     'update'),                              
(48 ,       'device_class',                     'vibration'),                           
(49 ,       'device_class',                     'window'),                              
(50 ,       'description',                      'string'),                              
(51 ,       'message',                          'string'),                              
(52 ,       'all_day',                          'string'),                              
(53 ,       'start_time',                       'string'),                              
(54 ,       'end_time',                         'string'),                              
(55 ,       'location',                         'string'),                              
(56 ,       'event',                            'string'),                              
(57 ,       'offset',                           'string'),                              
(58 ,       'main',                             'idle'),                                
(59 ,       'main',                             'recording'),                           
(60 ,       'main',                             'streaming'),                           
(61 ,       'frontend_stream_type',             'hls'),                                 
(62 ,       'frontend_stream_type',             'web_rtc'),                             
(63 ,       'main',                             'auto'),                                
(64 ,       'main',                             'cool'),                                
(65 ,       'main',                             'heat'),                                
(66 ,       'main',                             'heat_cool'),                           
(67 ,       'main',                             'dry'),                                 
(68 ,       'main',                             'fan_only'),                            
(69 ,       'current_humidity',                 'float'),                               
(70 ,       'current_temperature',              'float'),                               
(71 ,       'max_humidity',                     'float'),                               
(72 ,       'max_temp',                         'float'),                               
(73 ,       'min_humidity',                     'float'),                               
(74 ,       'min_temp',                         'float'),                               
(75 ,       'precision',                        'float'),                               
(76 ,       'humidity',                         'float'),                               
(77 ,       'temperature',                      'float'),                               
(78 ,       'target_temp_high',                 'float'),                               
(79 ,       'target_temp_low',                  'float'),                               
(80 ,       'target_temp_step',                 'int'),                                 
(81 ,       'temperature_unit',                 'string'),                              
(82 ,       'hvac_action',                      'preheating'),                          
(83 ,       'hvac_action',                      'heating'),                             
(84 ,       'hvac_action',                      'cooling'),                             
(85 ,       'hvac_action',                      'drying'),                              
(86 ,       'hvac_action',                      'fan'),                                 
(87 ,       'hvac_action',                      'defrosting'),                          
(88 ,       'hvac_action',                      'off'),                                 
(89 ,       'hvac_action',                      'idle'),                                
(90 ,       'fan_mode',                         'on'),                                  
(91 ,       'fan_mode',                         'off'),                                 
(92 ,       'fan_mode',                         'auto_high'),                           
(93 ,       'fan_mode',                         'auto_low'),                            
(94 ,       'fan_mode',                         'on_low'),                              
(95 ,       'fan_mode',                         'on_medium'),                           
(96 ,       'fan_mode',                         'on_high'),                             
(97 ,       'fan_mode',                         'middle'),                              
(98 ,       'fan_mode',                         'focus'),                               
(99 ,       'fan_mode',                         'diffuse'),                             
(100,       'swing_mode',                       'off'),                                 
(101,       'swing_mode',                       'auto'),                                
(102,       'swing_mode',                       '1'),                                   
(103,       'swing_mode',                       '2'),                                   
(104,       'swing_mode',                       '3'),                                   
(105,       'swing_mode',                       'vertical'),                            
(106,       'swing_mode',                       'horizontal'),                          
(107,       'swing_mode',                       'both'),                                
(108,       'main',                             'string'),                              
(109,       'command',                          'string'),                              
(110,       'main',                             'closed'),                              
(111,       'main',                             'closing'),                             
(112,       'main',                             'open'),                                
(113,       'main',                             'opening'),                             
(114,       'device_class',                     'awning'),                              
(115,       'device_class',                     'blind'),                               
(116,       'device_class',                     'curtain'),                             
(117,       'device_class',                     'damper'),                              
(118,       'device_class',                     'garage'),                              
(119,       'device_class',                     'gate'),                                
(120,       'device_class',                     'shade'),                               
(121,       'device_class',                     'sutter'),                              
(122,       'main',                             'home'),                                
(123,       'main',                             'not_home'),                            
(124,       'source_type',                      'gps'),                                 
(125,       'source_type',                      'router'),                              
(126,       'source_type',                      'bluetooth'),                           
(127,       'source_type',                      'bluetooth_le'),                        
(128,       'longitude',                        'float'),                               
(129,       'latitude',                         'float'),                               
(130,       'location_accuracy',                'string'),                              
(131,       'battery',                          'int'),                                 
(132,       'event_type',                       'pressed'),                             
(133,       'event_type',                       'call_service'),                        
(134,       'event_type',                       'component_loaded'),                    
(135,       'event_type',                       'core_config_updated'),                 
(136,       'event_type',                       'data_entry_flow_progressed'),          
(137,       'event_type',                       'homeassistant_start'),                 
(138,       'event_type',                       'homeassistant_started'),               
(139,       'event_type',                       'homeassistant_stop'),                  
(140,       'event_type',                       'homeassistant_final_write'),           
(141,       'event_type',                       'logbook_entry'),                       
(142,       'event_type',                       'service_registered'),                  
(143,       'event_type',                       'service_removed'),                     
(144,       'event_type',                       'state_changed'),                       
(145,       'event_type',                       'themes_updated'),                      
(146,       'event_type',                       'user_added'),                          
(147,       'event_type',                       'user_removed'),                        
(148,       'event_type',                       'automation_reloaded'),                 
(149,       'event_type',                       'automation_triggered'),                
(150,       'event_type',                       'scene_reloaded'),                      
(151,       'event_type',                       'script_started'),                      
(152,       'event_type',                       'area_registry_updated'),               
(153,       'event_type',                       'category_registry_updated'),           
(154,       'event_type',                       'device_registry_updated'),             
(155,       'event_type',                       'entity_registry_updated'),             
(156,       'event_type',                       'string'),                              
(157,       'event_data',                       'dict'),                                
(158,       'context',                          'dict'),                                
(159,       'percentage',                       'int'),                                 
(160,       'percentage_step',                  'int'),                                 
(161,       'oscillating',                      'bool'),                                
(162,       'direction',                        'forward'),                             
(163,       'direction',                        'reverse'),                             
(164,       'action',                           'off'),                                 
(165,       'action',                           'idle'),                                
(166,       'action',                           'humidifying'),                         
(167,       'action',                           'drying'),                              
(168,       'device_class',                     'humidifier'),                          
(169,       'device_class',                     'dehumidifier'),                        
(170,       'main',                             'mowing'), 	                        
(171,       'main',                             'docked'),	                        
(172,       'main',                             'paused'),	                        
(173,       'main',                             'error'),                               
(174,       'effect',                           'rainbow'),                             
(175,       'effect',                           'none'),                                
(176,       'min_color_temp_kelvin',            'int'),                                 
(177,       'max_color_temp_kelvin',            'int'),                                 
(178,       'color_mode',                       'color_temp'),                          
(179,       'color_mode',                       'hs'),                                  
(180,       'brightness',                       'int'),                                 
(181,       'color_temp_kelvin',                'int'),                                 
(182,       'hs_color',                         'tuple[float, float]'),                 
(183,       'rgb_color',                        'tuple[int, int, int]'),                
(184,       'xy_color',                         'tuple[float, float]'),                 
(185,       'rgbw_color',                       'tuple[int, int, int, int]'),           
(186,       'rgbww_color',                      'tuple[int, int, int, int, int]'),      
(187,       'main',                             'jammed'),                              
(188,       'main',                             'locked'),                              
(189,       'main',                             'locking'),                             
(190,       'main',                             'unlocked'),                            
(191,       'main',                             'unlocking'),                           
(192,       'main',                             'playing'),                             
(193,       'main',                             'standby'),                             
(194,       'main',                             'buffering'),                           
(195,       'volume_level',                     'float'),                               
(196,       'is_volume_muted',                  'bool'),                                
(197,       'volume_step',                      'float'),                               
(198,       'media_content_id',                 'string'),                              
(199,       'media_content_type',               'album'),                               
(200,       'media_content_type',               'app'),                                 
(201,       'media_content_type',               'artist'),                              
(202,       'media_content_type',               'channel'),                             
(203,       'media_content_type',               'channels'),                            
(204,       'media_content_type',               'composer'),                            
(205,       'media_content_type',               'contibuting_artist'),                  
(206,       'media_content_type',               'episode'),                             
(207,       'media_content_type',               'game'),                                
(208,       'media_content_type',               'genre'),                               
(209,       'media_content_type',               'image'),                               
(210,       'media_content_type',               'movie'),                               
(211,       'media_content_type',               'music'),                               
(212,       'media_content_type',               'playlist'),                            
(213,       'media_content_type',               'podcast'),                             
(214,       'media_content_type',               'season'),                              
(215,       'media_content_type',               'track'),                               
(216,       'media_content_type',               'tvshow'),                              
(217,       'media_content_type',               'url'),                                 
(218,       'media_content_type',               'video'),                               
(219,       'app_name',                         'string'),                              
(220,       'group_members',                    'list[string]'),                        
(221,       'media_album_artist',               'string'),                              
(222,       'media_album_name',                 'string'),                              
(223,       'media_artist',                     'string'),                              
(224,       'media_channel',                    'string'),                              
(225,       'media_duration',                   'int'),                                 
(226,       'media_episode',                    'string'),                              
(227,       'media_playlist',                   'string'),                              
(228,       'media_position',                   'int'),                                 
(229,       'media_season',                     'string'),                              
(230,       'media_series_title',               'string'),                              
(231,       'media_title',                      'string'),                              
(232,       'media_track',                      'int'),                                 
(233,       'repeat',                           'off'),                                 
(234,       'repeat',                           'one'),                                 
(235,       'repeat',                           'all'),                                 
(236,       'shuffle',                          'bool'),                                
(237,       'source',                           'dvd'),                                 
(238,       'source',                           'youtube'),                             
(239,       'sound_mode',                       'music'),                               
(240,       'sound_mode',                       'movie'),                               
(241,       'device_class',                     'tv'),                                  
(242,       'device_class',                     'speaker'),                             
(243,       'device_class',                     'receiver'),                            
(244,       'main',                             'float'),                               
(245,       'min',                              'float'),                               
(246,       'max',                              'float'),                               
(247,       'step',                             'float'),
(248,       'mode',                             'string'),                               
(249,       'activity',                         'string'),                              
(250,       'current_activity',                 'string'),                              
(251,       'id',                               'string'),                              
(252,       'entity_id',                        'string'),                              
(253,       'main', 	                        'option'),                              
(254,       'options',                          'list[string]'),                        
(255,       'device_class',                     'apparent_power'),                      
(256,       'device_class',                     'aqi'),                                 
(257,       'device_class',                     'atmospheric_pressure'),                
(258,       'device_class',                     'conductivity'),                        
(259,       'device_class',                     'carbon_dioxide'),                      
(260,       'device_class',                     'carbon_monoxide'),                     
(261,       'device_class',                     'current'),                             
(262,       'device_class',                     'data_rate'),                           
(263,       'device_class',                     'data_size'),                           
(264,       'device_class',                     'distance'),                            
(265,       'device_class',                     'duration'),                            
(266,       'device_class',                     'energy'),                              
(267,       'device_class',                     'energy_storage'),                      
(268,       'device_class',                     'frequency'),                           
(269,       'device_class',                     'humidity'),                            
(270,       'device_class',                     'illuminance'),                         
(271,       'device_class',                     'irradiance'),                          
(272,       'device_class',                     'monetary'),                            
(273,       'device_class',                     'nitrogen_dioxide'),                    
(274,       'device_class',                     'nitrogen_monoxide'),                   
(275,       'device_class',                     'nitrous_oxide'),                       
(276,       'device_class',                     'ozone'),                               
(277,       'device_class',                     'ph'),                                  
(278,       'device_class',                     'pm1'),                                 
(279,       'device_class',                     'pm10'),                                
(280,       'device_class',                     'pm25'),                                
(281,       'device_class',                     'power_factor'),                        
(282,       'device_class',                     'precipitation'),                       
(283,       'device_class',                     'precipitation_intensity'),             
(284,       'device_class',                     'pressure'),                            
(285,       'device_class',                     'reactive_power'),                      
(286,       'device_class',                     'signal_strength'),                     
(287,       'device_class',                     'sound_pressure'),                      
(288,       'device_class',                     'speed'),                               
(289,       'device_class',                     'sulphur_dioxide'),                     
(290,       'device_class',                     'temperature'),                         
(291,       'device_class',                     'volatile_organic_compounds'),          
(292,       'device_class',                     'volatile_organic_compounds_parts'),    
(293,       'device_class',                     'voltage'),                             
(294,       'device_class',                     'volume'),                              
(295,       'device_class',                     'volume_storage'),                      
(296,       'device_class',                     'volume_flow_rate'),                    
(297,       'device_class',                     'water'),                               
(298,       'device_class',                     'weight'),                              
(299,       'device_class',                     'wind_speed'),                          
(300,       'unit_of_measurement',              'string'),                              
(301,       'battery_level',                    'int'),                                 
(302,       'device_class',                     'date'),                                
(303,       'device_class',                     'timestamp'),                           
(304,       'available_tones',                  'list[string]'),                        
(305,       'device_class',                     'switch'),                              
(306,       'device_class',                     'outlet'),                              
(307,       'mode',                             'text'),                                
(308,       'mode',                             'password'),                            
(309,       'pattern',                          'string'),                              
(310,       'main',                             'int'),                                 
(311,       'auto_update',                      'bool'),                                
(312,       'installed_version',                'string'),                              
(313,       'in_progress',                      'int'),                                 
(314,       'release_summary',                  'string'),                              
(315,       'release_url',                      'string'),                              
(316,       'current_version',                  'string'),                              
(317,       'skipped_version',                  'string'),                              
(318,       'title',                            'string'),                              
(319,       'latest_version',                   'string'),                              
(320,       'device_class',                     'firmware'),                            
(321,       'main',                             'cleaning'),                            
(322,       'main',                             'returning'),                           
(323,       'battery_icon',                     'string'),                              
(324,       'cleaned_area',                     'float'),                               
(325,       'fan_speed',                        'min'),                                 
(326,       'fan_speed',                        'medium'),                              
(327,       'fan_speed',                        'high'),                                
(328,       'fan_speed',                        'max'),                                 
(329,       'current_position',                 'int'),                                 
(330,       'main',                             'eco'),                                 
(331,       'main',                             'electric'),                            
(332,       'main',                             'performance'),                         
(333,       'main',                             'high_demand'),                         
(334,       'main',                             'heat_pump'),                           
(335,       'main',                             'gas'),                                 
(336,       'operation_mode',                   'eco'),                                 
(337,       'operation_mode',                   'electric'),                            
(338,       'operation_mode',                   'performance'),                         
(339,       'operation_mode',                   'high_demand'),                         
(340,       'operation_mode',                   'heat_pump'),                           
(341,       'operation_mode',                   'gas'),                                 
(342,       'operation_mode',                   'off'),                                 
(343,       'away_mode',                        'on'),                                  
(344,       'away_mode',                        'off'),                                 
(345,       'main',                             'clear-night'),                         
(346,       'main',                             'cloudy'),                              
(347,       'main',                             'exceptional'),                         
(348,       'main',                             'fog'),                                 
(349,       'main',                             'hail'),                                
(350,       'main',                             'lightning'),                           
(351,       'main',                             'lightning-rainy'),                     
(352,       'main',                             'partlycloudy'),                        
(353,       'main',                             'pouring'),                             
(354,       'main',                             'rainy'),                               
(355,       'main',                             'snowy'),                               
(356,       'main',                             'snowy-rainy'),                         
(357,       'main',                             'sunny'),                               
(358,       'main',                             'windy'),                               
(359,       'main',                             'windy-variant'),                       
(360,       'attribution',                      'string'),                              
(361,       'apparent_temperature',             'float'),                               
(362,       'pressure',                         'flaot'),                               
(363,       'pressure_unit',                    'string'),                              
(364,       'wind_speed',                       'float'),                               
(365,       'wind_speed_unit',                  'string'),                              
(366,       'wind_bearing',                     'string'),                              
(367,       'wind_gust_speed',                  'float'),                               
(368,       'visibility',                       'float'),                               
(369,       'visibility_unit',                  'string'),                              
(370,       'cloud_coverage',                   'int'),                                 
(371,       'dew_point',                        'float'),                               
(372,       'ozone',                            'float'),                               
(373,       'uv_index',                         'float'),                               
(374,       'precipitation_unit',               'string'),                              
(375,       'event',                            'start'),                               
(376,       'event',                            'shutdown'),                            
(377,       'payload',                          'string'),                              
(378,       'qos',                              '0'),                                   
(379,       'qos',                              '1'),                                   
(380,       'qos',                              '2'),                                   
(381,       'main',                             'above_horizon'),                       
(382,       'main',                             'below_horizon'),                       
(383,       'azimuth',                          'float'),                               
(384,       'elevation',                        'float'),                               
(385,       'next_dawn',                        'string'),                              
(386,       'next_dusk',                        'string'),                              
(387,       'next_midnight',                    'string'),                              
(388,       'next_noon',                        'string'),                              
(389,       'next_rising',                      'string'),                              
(390,       'next_setting',                     'string'),                              
(391,       'rising',                           'bool'),                                
(392,       'event',                            'sunrise'),                             
(393,       'event',                            'sunset'),                              
(394,       'device_id',                        'string'),                              
(395,       'tag_id',                           'string'),                              
(396,       'update_type',                      'added'),                               
(397,       'update_type',                      'updated'),                             
(398,       'update_type',                      'removed'),                             
(399,       'update_type',                      'current'),                             
(400,       'notification_id',                  'string'),                              
(401,       'allowed_method',                   'POST'),                                
(402,       'allowed_method',                   'PUT'),                                 
(403,       'allowed_method',                   'HEAD'),                                
(404,       'allowed_method',                   'GET'),                                 
(405,       'local_only',                       'bool'),                                
(406,       'radius',                           'int'),                                 
(407,       'passive',                          'bool'),                                
(408,       'persons',                          'list[string]'),                                                       
(409,       'domain',                           'string'),                              
(410,       'type',                             'turned_on'),                           
(411,       'type',                             'turned_off'),                          
(412,       'type',                             'is_on'),                               
(413,       'type',                             'is_off'),                              
(414,       'type',                             'turn_on'),                             
(415,       'type',                             'turn_off'),                            
(416,       'type',                             'toggle'),                              
(417,       'weekday',                          'mon'),                                 
(418,       'weekday',                          'tue'),                                 
(419,       'weekday',                          'wed'),                                 
(420,       'weekday',                          'thu'),                                 
(421,       'weekday',                          'fri'),                                 
(422,       'weekday',                          'sat'),                                 
(423,       'weekday',                          'sun'),                                 
(424,       'last_triggered',                   'datetime'),                            
(425,       'mode',                             'single'),                              
(426,       'mode',                             'restart'),                             
(427,       'mode',                             'queued'),                              
(428,       'mode',                             'parallel'),                            
(429,       'current',                          'int'),
(430,       'device_trackers',                  'list[string]'),      
(431,       'user_id',                          'string'),            
(432,       'source',                           'string'),                                                                                                                                                                                                                                                                  
]   

possible_values = dict()    

for e in all_added: 
    e_mix = e[1] + e[2]
    if e_mix not in possible_values:
        possible_values[e_mix] = e[0]

print("values: " + str(len(possible_values.items())))

counter = 1

for e in possible_values:
    if counter > 1:
        while possible_values[e] > counter:
            print(str(counter) + '\t' + str(e))
            counter += 1 
    counter += 1
