alias: Turn off living room main light with a switch
description: >-
  This automation turns off the main light in the living room when the switch is
  turned off. If the media player is playing, it will pause the media player and
  turn off the automation that turns on the main light in the living room. After
  1 minute, it will turn on the automation that turns on the main light in the
  living room.
trigger:
  - platform: state
    entity_id:
      - switch.main_light_living_room
    to: "off"
  - platform: event
    event_type: call_service
    event_data:
      service_call_id: toggle_main_light_switch
condition:
  - condition: state
    entity_id: light.main_light_living_room
    state: "off"
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: media_player.living_room
            state: playing
        sequence:
          - service: media_player.media_pause
            metadata: {}
            data: {}
  - service: automation.turn_off
    metadata: {}
    data:
      stop_actions: true
    target:
      entity_id: automation.turn_on_living_room_main_light
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: automation.turn_on
    target:
      entity_id: automation.turn_on_living_room_main_light
    data: {}
mode: single
