alias: TV-Lighting-Living-Room
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.tv_state
    to: "on"
condition: []
action:
  - choose:
      - conditions:
          - condition: time
            after: "20:30:00"
        sequence:
          - if:
              - condition: state
                entity_id: light.main_light_living_room
                state: "on"
              - condition: state
                entity_id: light.couch_lights_living_room
                state: "off"
            then:
              - action: light.turn_on
                metadata: {}
                data: {}
                target:
                  entity_id:
                    - light.couch_lights_living_room
              - action: light.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id: light.main_light_living_room
            else:
              - event: call_service
                event_data:
                  action: light.turn_off
                  target:
                    entity_id: light.main_light_living_room
      - conditions:
          - condition: numeric_state
            entity_id: sensor.sun_solar_elevation
            above: 10
        sequence:
          - action: cover.set_cover_position
            metadata: {}
            data:
              position: 95
            target:
              entity_id: cover.living_room_window
          - action: cover.set_cover_tilt_position
            metadata: {}
            data:
              tilt_position: 75
            target:
              entity_id: cover.living_room_window
mode: single
