alias: Sun depended cover controll in the living room
description: ""
trigger:
  - platform: state
    entity_id:
      - sun.sun
action:
  - condition: and
    conditions:
      - condition: template
        value_template: >
          {{ ((state_attr(cover_entity.entity_id,'current_position') | float -
          cover_height | float) | abs > change_threshold) or (cover_height in
          [default_height, default_template])}}
      - condition: template
        value_template: >
          {{now() - timedelta(minutes=time_out) >=
          states[cover_entity.entity_id].last_updated }}
  - action: cover.set_cover_position
    data:
      position: "{{ cover_height | int(0) }}"
    target:
      entity_id: cover.blinds_living_room
variables:
  cover_entity:
    entity_id: cover.blinds_living_room
  azimuth: 180
  distance: 0.9
  max_height: 2
  min_height: 0.2
  default_height: 80
  min_position: 0
  degrees: 90
  default_template: ""
  azimuth_left: 90
  azimuth_right: 90
  max_elevation: 90
  min_elevation: 0
  cover_height: >
    {%- set deg2rad = pi/180 -%} {# normalize in range [0,1] #} {%- macro
    norm(x, min, max) %}
      {{ (x - min) / (max - min) }}
    {%- endmacro %} {# convert blind height h to percentage [0,100] #} {%- macro
    h2perc(x) %}
      {{ 100 * float(norm(x, h_min, h_max)) }}
    {%- endmacro %} {# clip value between [min, max] #} {%- macro clipv(x,
    x_min, x_max) %}
      {{ max(min(x, x_max), x_min) }}
    {%- endmacro %} {# constants #} {%- set win_azi = azimuth -%} {%- set
    left_azi = azimuth_left | default(90) -%} {%- set right_azi = azimuth_right
    | default(90) -%} {%- set elev_high = deg2rad * (max_elevation |
    default(90)) -%} {# Maximum: 90 #} {%- set elev_low = deg2rad *
    (min_elevation| default(0)) -%} {# Minimum: 0 #} {%- set d = distance |
    default(0.5) -%} {%- set h_max = max_height | default(2.10) -%} {%- set
    h_min = min_height | default(0) -%} {%- set deg = degrees | default(90) -%}
    {%- set def = default_height | default(60) -%} {%- set min_pos =
    min_position | default(0) -%} {%- set def_temp = default_template |
    default('') -%} {% if def_temp | int(-1) >= 0 %}
      {% set def = def_temp %}
    {%endif%}

    {# FOV #} {%- if left_azi != right_azi-%}
      {%- set azi_left = deg2rad * -left_azi -%} {# Minimum: -90 #}
      {%- set azi_right = deg2rad * right_azi -%} {# Maximum: 90 #}
    {%-else-%}
      {%- set azi_left = deg2rad * -deg -%} {# Minimum: -90 #}
      {%- set azi_right = deg2rad * deg -%} {# Maximum: 90 #}
    {%-endif-%} {%- set fov = deg2rad * deg -%} {# get sun elevation / azimuth
    from sun.sun #} {%- set sun_azi = state_attr('sun.sun', 'azimuth') -%} {%-
    set sun_ele = state_attr('sun.sun', 'elevation') -%} {# default height, when
    automatic control is off. #} {%- set def_h = def / 100 * h_max -%} {%- set
    alpha = deg2rad * sun_ele -%} {%- set gamma = deg2rad * (win_azi - sun_azi)
    -%}     {%- set h = (d / cos(gamma)) * tan(alpha) -%} {# gamma is outside of
    FOV #} {%- if gamma < azi_left or gamma > azi_right or alpha < elev_low or
    alpha > elev_high -%}
      {{ clipv(h2perc(def_h) | round(0) | int , 0, 100) }}
    {# gamma is inside of FOV #} {%- else -%}  
      {{ clipv(h2perc(h) | round(0) | int , min_pos, 100) }}
    {%- endif -%}
  change_threshold: 0
  time_out: 1
  condition_mode: and
mode: single
