alias: Turn on living room main light
description: >-
  This automation turns on the main light in the living room when a movement or a
  person is detected in the living room. If the sun has set and the main light in
  the living room is on, it will turn on the ceiling lights in the living room. If
  Krista is in the living room and the media player is not playing, it will turn on
  the media player in the living room.
trigger:
  - alias: If a movement is detected
    platform: state
    entity_id:
      - binary_sensor.moving_living_room
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.person_living_room
    from: "off"
    to: "on"
    alias: If a person is detected
condition:
  - alias: If the sun has set
    condition: sun
    after: sunrise
  - condition: state
    entity_id: light.main_light_living_room
    state: "off"
    alias: If the main light is on
action:
  - alias: Turn on the ceiling lights
    action: light.turn_on
    data: {}
    target:
      entity_id: light.ceiling_lights
  - choose:
      - conditions:
          - alias: If Krista is in the living room
            condition: state
            entity_id: sensor.whos_in_living_room
            state: Krista
          - condition: not
            conditions:
              - condition: state
                entity_id: media_player.living_room
                state: playing
        sequence:
          - alias: turn on the media player
            action: media_player.media_play
            target:
              entity_id: media_player.living_room
            data: {}
mode: single
