{
    'x72': 15,
    'x73': 16,
    'x74': 17,
    'x75': 18,
    'x14': 19,
    'x15': 20,

}
old_list = [
[1  ,     'main',     'None'],	                                   
[2  ,     'main',     'disarmed'],	                               
[3  ,     'main',     'armed_home'],	                           
[4  ,     'main',     'armed_away'],	                           
[5  ,     'main',     'armed_night'],	                           
[6  ,     'main',     'armed_vacation'],	                       
[7  ,     'main',     'armed_custom_bypass'],                      
[8  ,     'main',     'pending'],	                               
[9  ,     'main',     'arming'],	                               
[10 ,    'main',     'disarming'],	                               
[11 ,    'main',     'triggered'],                                 
[12 ,    'main',     'unknown'],	                               
[13 ,    'main',     'unavailable'],                               
[14 ,    'main',     'on'],	                                       
[15 ,    'main',     'off'],	                                   
[16 ,    'main',     'idle'],                                      
[17 ,    'main',     'recording'],                                 
[18 ,    'main',     'streaming'],                                 
[19 ,    'main',     'auto'],                                      
[20 ,    'main',     'cool'],                                      
[21 ,    'main',     'heat'],                                      
[22 ,    'main',     'heat_cool'],                                 
[23 ,    'main',     'dry'],                                       
[24 ,    'main',     'fan_only'],                                  
[25 ,    'main',     'string'],                                    
[26 ,    'main',     'closed'],                                    
[27 ,    'main',     'closing'],                                   
[28 ,    'main',     'open'],                                      
[29 ,    'main',     'opening'],                                   
[30 ,    'main',     'home'],                                      
[31 ,    'main',     'not_home'],                                  
[32 ,    'main',     'mowing'], 	                               
[33 ,    'main',     'docked'],	                                   
[34 ,    'main',     'paused'],	                                   
[35 ,    'main',     'error'],       	                           
[36 ,    'main',     'jammed'],                                    
[37 ,    'main',     'locked'],                                    
[38 ,    'main',     'locking'],                                   
[39 ,    'main',     'unlocked'],                                  
[40 ,    'main',     'unlocking'],                                 
[41 ,    'main',     'playing'],                                   
[42 ,    'main',     'standby'],                                   
[43 ,    'main',     'buffering'],                                 
[44 ,    'main',     'float'],                                     
[45 ,    'main', 	'option'],                                     
[46 ,    'main',     'int'],                                   
[47 ,    'main',     'cleaning'],                                  
[48 ,    'main',     'returning'],                                 
[49 ,    'main',     'eco'],                                       
[50 ,    'main',     'electric'],                                  
[51 ,    'main',     'performance'],                               
[52 ,    'main',     'high_demand'],                               
[53 ,    'main',     'heat_pump'],                                 
[54 ,    'main',     'gas'],                                       
[55 ,    'main',     'clear-night'],                               
[56 ,    'main',     'cloudy'],                                    
[57 ,    'main',     'exceptional'],                               
[58 ,    'main',     'fog'],                                       
[59 ,    'main',     'hail'],                                      
[60 ,    'main',     'lightning'],                                 
[61 ,    'main',     'lightning-rainy'],                           
[62 ,    'main',     'partlycloudy'],                              
[63 ,    'main',     'pouring'],                                   
[64 ,    'main',     'rainy'],                                     
[65 ,    'main',     'snowy'],                                     
[66 ,    'main',     'snowy-rainy'],                               
[67 ,    'main',     'sunny'],                                     
[68 ,    'main',     'windy'],                                     
[69 ,    'main',     'windy-variant'],                             
[70 ,    'code_format',          'number'],                        
[71 ,    'code_format',          'text'],                          
[72 ,    'changed_by',           'string'],                        
[73 ,    'code_arm_required',    'string'],                        
[74 ,    'supported_features',   'int'],                           
[75 ,    'device_class',         'battery'],                       
[76 ,    'device_class',         'battery_charging'],              
[77 ,    'device_class',         'co'],                            
[78 ,    'device_class',         'cold'],                          
[79 ,    'device_class',         'connectivity'],                  
[80 ,    'device_class',         'door'],                          
[81 ,    'device_class',         'garage_door'],                   
[82 ,    'device_class',         'gas'],                           
[83 ,    'device_class',         'heat'],                          
[84 ,    'device_class',         'light'],                         
[85 ,    'device_class',         'lock'],                          
[86 ,    'device_class',         'moisture'],                      
[87 ,    'device_class',         'motion'],                        
[88 ,    'device_class',         'moving'],                        
[89 ,    'device_class',         'occupancy'],                     
[90 ,    'device_class',         'opening'],                       
[91 ,    'device_class',         'plug'],                          
[92 ,    'device_class',         'power'],                         
[93 ,    'device_class',         'presence'],                      
[94 ,    'device_class',         'problem'],                       
[95 ,    'device_class',         'running'],                       
[96 ,    'device_class',         'safety'],                        
[97 ,    'device_class',         'smoke'],                         
[98 ,    'device_class',         'sound'],                         
[99 ,    'device_class',         'tamper'],                        
[100,   'device_class',         'update'],                         
[101,   'device_class',         'vibration'],                      
[102,   'device_class',         'window'],                         
[103,   'description',          'string'],                         
[104,   'message',              'string'],                         
[105,   'all_day',              'string'],                         
[106,   'start_time',           'string'],                         
[107,   'end_time',             'string'],                         
[108,   'location',             'string'],                         
[109,   'frontend_stream_type', 'hls'],                            
[110,   'frontend_stream_type', 'web_rtc'],                        
[111,   'current_humidity',     'float'],                          
[112,   'current_temperature',  'float'],                          
[113,   'max_humidity',         'float'],                          
[114,   'max_temp',             'float'],                          
[115,   'min_humidity',         'float'],                          
[116,   'min_temp',             'float'],                          
[117,   'precision',            'float'],                          
[118,   'humidity',             'float'],                          
[119,   'temperature',          'float'],                          
[120,   'target_temp_high',     'float'],                          
[121,   'target_temp_low',      'float'],                          
[122,   'target_temp_step',     'int'],                        
[123,   'temperature_unit',     'string'],                         
[124,   'hvac_action',          'preheating'],                     
[125,   'hvac_action',          'heating'],                        
[126,   'hvac_action',          'cooling'],                        
[127,   'hvac_action',          'drying'],                         
[128,   'hvac_action',          'fan'],                            
[129,   'hvac_action',          'defrosting'],                     
[130,   'hvac_action',          'off'],                            
[131,   'hvac_action',          'idle'],                           
[132,   'fan_mode',             'on'],                             
[133,   'fan_mode',             'off'],                            
[134,   'fan_mode',             'auto_high'],                      
[135,   'fan_mode',             'auto_low'],                       
[136,   'fan_mode',             'on_low'],                         
[137,   'fan_mode',             'on_medium'],                      
[138,   'fan_mode',             'on_high'],                        
[139,   'fan_mode',             'middle'],                         
[140,   'fan_mode',             'focus'],                          
[141,   'fan_mode',             'diffuse'],                        
[142,   'swing_mode',           'off'],                            
[143,   'swing_mode',           'auto'],                           
[144,   'swing_mode',           '1'],                              
[145,   'swing_mode',           '2'],                              
[146,   'swing_mode',           '3'],                              
[147,   'swing_mode',           'vertical'],                       
[148,   'swing_mode',           'horizontal'],                     
[149,   'swing_mode',           'both'],                           
[150,   'device_class',         'awning'],                         
[151,   'device_class',         'blind'],                          
[152,   'device_class',         'curtain'],                        
[153,   'device_class',         'damper'],                         
[154,   'device_class',         'garage'],                         
[155,   'device_class',         'gate'],                           
[156,   'device_class',         'shade'],                          
[157,   'device_class',         'sutter'],                         
[158,   'source_type',          'gps'],                            
[159,   'source_type',          'router'],                         
[160,   'source_type',          'bluetooth'],                      
[161,   'source_type',          'bluetooth_le'],                   
[162,   'longitude',            'float'],                          
[163,   'latitude',             'float'],                          
[164,   'location_accuracy',    'string'],                         
[165,   'battery',              'int'],                            
[166,   'event_type',           'pressed'],                        
[167,   'event_type',           'call_service'],                   
[168,   'event_type',           'component_loaded'],               
[169,   'event_type',           'core_config_updated'],            
[170,   'event_type',           'data_entry_flow_progressed'],     
[171,   'event_type',           'homeassistant_start'],            
[172,   'event_type',           'homeassistant_started'],          
[173,   'event_type',           'homeassistant_stop'],             
[174,   'event_type',           'homeassistant_final_write'],      
[175,   'event_type',           'logbook_entry'],                  
[176,   'event_type',           'service_registered'],             
[177,   'event_type',           'service_removed'],                
[178,   'event_type',           'state_changed'],                  
[179,   'event_type',           'themes_updated'],                 
[180,   'event_type',           'user_added'],                     
[181,   'event_type',           'user_removed'],                   
[182,   'event_type',           'automation_reloaded'],            
[183,   'event_type',           'automation_triggered'],           
[184,   'event_type',           'scene_reloaded'],                 
[185,   'event_type',           'script_started'],                 
[186,   'event_type',           'area_registry_updated'],          
[187,   'event_type',           'category_registry_updated'],      
[188,   'event_type',           'device_registry_updated'],        
[189,   'event_type',           'entity_registry_updated'],        
[190,   'event_type',           'string'],                         
[191,   'percentage',           'int'],                        
[192,   'percentage_step',      'int'],                        
[193,   'oscillating',          'bool'],                           
[194,   'direction',            'forward'],                        
[195,   'direction',            'reverse'],                        
[196,   'action',               'off'],                            
[197,   'action',               'idle'],                           
[198,   'action',               'humidifying'],                    
[199,   'action',               'drying'],                         
[200,   'device_class',         'humidifier'],                     
[201,   'device_class',         'dehumidifier'],                   
[202,   'effect',               'rainbow'],                        
[203,   'effect',               'none'],                           
[204,   'min_color_temp_kelvin','int'],                            
[205,   'max_color_temp_kelvin','int'],                            
[206,   'color_mode',           'color_temp'],                     
[207,   'color_mode',           'hs'],                             
[208,   'brightness',           'int'],                        
[209,   'color_temp_kelvin',    'int'],                        
[210,   'hs_color',             'tuple[float, float]'],            
[211,   'rgb_color',            'tuple[int, int, int]'],           
[212,   'xy_color',             'tuple[float, float]'],            
[213,   'rgbw_color',           'tuple[int, int, int, int]'],      
[214,   'rgbww_color',          'tuple[int, int, int, int, int]'], 
[215,   'volume_level',         'float'],                          
[216,   'is_volume_muted',      'bool'],                           
[217,   'volume_step',          'float'],                          
[218,   'media_content_id',     'string'],                         
[219,   'media_content_type',   'album'],                          
[220,   'media_content_type',   'app'],                            
[221,   'media_content_type',   'artist'],                         
[222,   'media_content_type',   'channel'],                        
[223,   'media_content_type',   'channels'],                       
[224,   'media_content_type',   'composer'],                       
[225,   'media_content_type',   'contibuting_artist'],             
[226,   'media_content_type',   'episode'],                        
[227,   'media_content_type',   'game'],                           
[228,   'media_content_type',   'genre'],                          
[229,   'media_content_type',   'image'],                          
[230,   'media_content_type',   'movie'],                          
[231,   'media_content_type',   'music'],                          
[232,   'media_content_type',   'playlist'],                       
[233,   'media_content_type',   'podcast'],                        
[234,   'media_content_type',   'season'],                         
[235,   'media_content_type',   'track'],                          
[236,   'media_content_type',   'tvshow'],                         
[237,   'media_content_type',   'url'],                            
[238,   'media_content_type',   'video'],                          
[239,   'app_name',             'string'],                         
[240,   'group_members',        'list[string]'],                      
[241,   'media_album_artist',   'string'],                         
[242,   'media_album_name',     'string'],                         
[243,   'media_artist',         'string'],                         
[244,   'media_channel',        'string'],                         
[245,   'media_duration',       'int'],                        
[246,   'media_episode',        'string'],                         
[247,   'media_playlist',       'string'],                         
[248,   'media_position',       'int'],                        
[249,   'media_season',         'string'],                         
[250,   'media_series_title',   'string'],                         
[251,   'media_title',          'string'],                         
[252,   'media_track',          'int'],                        
[253,   'repeat',               'off'],                            
[254,   'repeat',               'one'],                            
[255,   'repeat',               'all'],                            
[256,   'shuffle',              'bool'],                           
[257,   'source',               'dvd'],                            
[258,   'source',               'youtube'],                        
[259,   'sound_mode',           'music'],                          
[260,   'sound_mode',           'movie'],                          
[261,   'device_class',         'tv'],                             
[262,   'device_class',         'speaker'],                        
[263,   'device_class',         'receiver'],                       
[264,   'min',                  'float'],                          
[265,   'max',                  'float'],                          
[266,   'step',                 'float'],                          
[267,   'mode',                 'string'],                         
[268,   'activity',             'string'],                         
[269,   'current_activity',     'string'],                         
[270,   'id',                   'string'],                         
[271,   'entity_id',            'string'],                         
[272,   'options', 	            'list[string]'],                   
[273,   'device_class',         'apparent_power'],                 
[274,   'device_class',         'aqi'],                            
[275,   'device_class',         'atmospheric_pressure'],           
[276,   'device_class',         'conductivity'],                   
[277,   'device_class',         'carbon_dioxide'],                 
[278,   'device_class',         'carbon_monoxide'],                
[279,   'device_class',         'current'],                        
[280,   'device_class',         'data_rate'],                      
[281,   'device_class',         'data_size'],                      
[282,   'device_class',         'distance'],                       
[283,   'device_class',         'duration'],                       
[284,   'device_class',         'energy'],                         
[285,   'device_class',         'energy_storage'],                 
[286,   'device_class',         'frequency'],                      
[287,   'device_class',         'humidity'],                       
[288,   'device_class',         'illuminance'],                    
[289,   'device_class',         'irradiance'],                     
[290,   'device_class',         'monetary'],                       
[291,   'device_class',         'nitrogen_dioxide'],               
[292,   'device_class',         'nitrogen_monoxide'],              
[293,   'device_class',         'nitrous_oxide'],                  
[294,   'device_class',         'ozone'],                          
[295,   'device_class',         'ph'],                             
[296,   'device_class',         'pm1'],                            
[297,   'device_class',         'pm10'],                           
[298,   'device_class',         'pm25'],                           
[299,   'device_class',         'power_factor'],                   
[300,   'device_class',         'precipitation'],                  
[301,   'device_class',         'precipitation_intensity'],        
[302,   'device_class',         'pressure'],                       
[303,   'device_class',         'reactive_power'],                 
[304,   'device_class',         'signal_strength'],                
[305,   'device_class',         'sound_pressure'],                 
[306,   'device_class',         'speed'],                          
[307,   'device_class',         'sulphur_dioxide'],                
[308,   'device_class',         'temperature'],                    
[309,   'device_class',         'volatile_organic_compounds'],     
[310,   'device_class',         'volatile_organic_compounds_parts'],
[311,   'device_class',         'voltage'],                        
[312,   'device_class',         'volume'],                         
[313,   'device_class',         'volume_storage'],                 
[314,   'device_class',         'volume_flow_rate'],               
[315,   'device_class',         'water'],                          
[316,   'device_class',         'weight'],                         
[317,   'device_class',         'wind_speed'],                     
[318,   'unit_of_measurement',  'string'],                         
[319,   'battery_level',        'int'],                            
[320,   'device_class',         'date'],                           
[321,   'device_class',         'timestamp'],                      
[322,   'available_tones',      'list[string]'],                   
[323,   'device_class',         'switch'],                         
[324,   'device_class',         'outlet'],                         
[325,   'mode',                 'text'],                           
[326,   'mode',                 'password'],                       
[327,   'pattern',              'string'],                         
[328,   'auto_update',          'bool'],                           
[329,   'installed_version',    'string'],                         
[330,   'in_progress',          'int'],                            
[331,   'release_summary',      'string'],                         
[332,   'release_url',          'string'],                         
[333,   'current_version',      'string'],                         
[334,   'skipped_version',      'string'],                         
[335,   'title',                'string'],                         
[336,   'latest_version',       'string'],                         
[337,   'device_class',         'firmware'],                       
[338,   'battery_icon',         'string'],                         
[339,   'cleaned_area',         'float'],                          
[340,   'fan_speed',            'min'],                            
[341,   'fan_speed',            'medium'],                         
[342,   'fan_speed',            'high'],                           
[343,   'fan_speed',            'max'],                            
[344,   'current_position',     'int'],                            
[345,   'operation_mode',       'eco'],                            
[346,   'operation_mode',       'electric'],                       
[347,   'operation_mode',       'performance'],                    
[348,   'operation_mode',       'high_demand'],                    
[349,   'operation_mode',       'heat_pump'],                      
[350,   'operation_mode',       'gas'],                            
[351,   'operation_mode',       'off'],                            
[352,   'away_mode',            'on'],                             
[353,   'away_mode',            'off'],                            
[354,   'attribution',          'string'],                         
[355,   'apparent_temperature', 'float'],                          
[356,   'pressure',             'flaot'],                          
[357,   'pressure_unit',        'string'],                         
[358,   'wind_speed',           'float'],                          
[359,   'wind_speed_unit',      'string'],                         
[360,   'wind_bearing',         'string'],                         
[361,   'wind_gust_speed',      'float'],                          
[362,   'visibility',           'float'],                          
[363,   'visibility_unit',      'string'],                         
[364,   'cloud_coverage',       'int'],                            
[365,   'dew_point',            'float'],                          
[366,   'ozone',                'float'],                          
[367,   'uv_index',             'float'],
[368,   'precipitation_unit',   'string']
]

new_list = [
[1  ,       'main',                           'None',	                                "--Unknown state."],
[2  ,       'main',                           'disarmed',	                            "--The alarm is disarmed (off)."],
[3  ,       'main',                           'armed_home',	                            "--The alarm is armed in home mode."],
[4  ,       'main',                           'armed_away',	                            "--The alarm is armed in away mode."],
[5  ,       'main',                           'armed_night',	                        "--The alarm is armed in night mode."],
[6  ,       'main',                           'armed_vacation',	                        "--The alarm is armed in vacation mode."],
[7  ,       'main',                           'armed_custom_bypass',                   "--The alarm is armed in bypass mode."],
[8  ,       'main',                           'pending',	                            "--The alarm is pending (towards triggered)."],
[9  ,       'main',                           'arming',	                                "--The alarm is arming."],
[10 ,       'main',                            'disarming',	                            "--The alarm is disarming."],
[11 ,       'main',                            'triggered',                            "--The alarm is triggered."],
[12 ,       'main',                            'unknown',	                            "--Unknown state."],
[13 ,       'main',                            'unavailable',                          "--The entity is not reachable."],
[14 ,       'code_format',                     'number',                               "--The code format of the alarm control panel."],
[15 ,       'code_format',                     'text',                                 "--The code format of the alarm control panel."],
[16 ,       'changed_by',                      'string',                               "--The alarm control panel got changed by a user."],
[17 ,       'code_arm_required',               'string',                               "--The code required to arm the alarm control panel."],
[18 ,       'supported_features',              'int',                                  "--The count of supported features of the alarm control panel."],
[19 ,       'template',                        'string',                               "--A template string for automations."],
[20 ,       'main',                            'on',                                   "--The sensor detects something."],
[21 ,       'main',                            'off',                                  "--The sensor detects nothing."],
[22 ,       'device_class',                     'battery',                             "--The device class of the binary sensor."],
[23 ,       'device_class',                     'battery_charging',                    "--The device class of the binary sensor."],
[24 ,       'device_class',                     'co',                                  "--The device class of the binary sensor."],
[25 ,       'device_class',                     'cold',                                "--The device class of the binary sensor."],
[26 ,       'device_class',                     'connectivity',                        "--The device class of the binary sensor."],
[27 ,       'device_class',                     'door',                                "--The device class of the binary sensor."],
[28 ,       'device_class',                     'garage_door',                         "--The device class of the binary sensor."],
[29 ,       'device_class',                     'gas',                                 "--The device class of the binary sensor."],
[30 ,       'device_class',                     'heat',                                "--The device class of the binary sensor."],
[31 ,       'device_class',                     'light',                               "--The device class of the binary sensor."],
[32 ,       'device_class',                     'lock',                                "--The device class of the binary sensor."],
[33 ,       'device_class',                     'moisture',                            "--The device class of the binary sensor."],
[34 ,       'device_class',                     'motion',                              "--The device class of the binary sensor."],
[35 ,       'device_class',                     'moving',                              "--The device class of the binary sensor."],
[36 ,       'device_class',                     'occupancy',                           "--The device class of the binary sensor."],
[37 ,       'device_class',                     'opening',                             "--The device class of the binary sensor."],
[38 ,       'device_class',                     'plug',                                "--The device class of the binary sensor."],
[39 ,       'device_class',                     'power',                               "--The device class of the binary sensor."],
[40 ,       'device_class',                     'presence',                            "--The device class of the binary sensor."],
[41 ,       'device_class',                     'problem',                             "--The device class of the binary sensor."],
[42 ,       'device_class',                     'running',                             "--The device class of the binary sensor."],
[43 ,       'device_class',                     'safety',                              "--The device class of the binary sensor."],
[44 ,       'device_class',                     'smoke',                               "--The device class of the binary sensor."],
[45 ,       'device_class',                     'sound',                               "--The device class of the binary sensor."],
[46 ,       'device_class',                     'tamper',                              "--The device class of the binary sensor."],
[47 ,       'device_class',                     'update',                              "--The device class of the binary sensor."],
[48 ,       'device_class',                     'vibration',                           "--The device class of the binary sensor."],
[49 ,       'device_class',                     'window',                              "--The device class of the binary sensor."],
[50 ,       'description',                      'string',                              "--The calender description."],
[51 ,       'message',                          'string',                              "--The calender message."],
[52 ,       'all_day',                          'string',                              "--The calender event is all day"],
[53 ,       'start_time',                       'string',                              "--The calender event start time"],
[54 ,       'end_time',                         'string',                              "--The calender event end time."],
[55 ,       'location',                         'string',                              "--The calender event location."],
[56 ,       'event',                             'string',                             "--Triggered with this event"],
[57 ,       'offset',                            'string',                             "--Offset of the trigger "],
[58 ,       'main',                             'idle',                                "--The camera observes."],
[59 ,       'main',                             'recording',                           "--The camera records the recording."],
[60 ,       'main',                             'streaming',                           "--The camera streams the recording."],
[61 ,       'frontend_stream_type',             'hls',                                 "--The streaming format in the ui of the camera."],
[62 ,       'frontend_stream_type',             'web_rtc',                             "--The streaming format in the ui of the camera."],
[63 ,       'main',                             'auto',                                "--The device is set to a schedule, learned behavior, AI."],
[64 ,       'main',                             'cool',                                "--The device is set to cool to a target temperature."],
[65 ,       'main',                             'heat',                                "--The device is set to heat to a target temperature."],
[66 ,       'main',                             'heat_cool',                           "--The device is set to heat/cool to a target temperature range."],
[67 ,       'main',                             'dry',                                 "--The device is set to dry/humidity mode."],
[68 ,       'main',                             'fan_only',                            "--The device only has the fan on. No heating or cooling taking place."],
[69 ,       'current_humidity',                 'float',                               "--The current humidity."],
[70 ,       'current_temperature',              'float',                               "--The current temperature."],
[71 ,       'max_humidity',                     'float',                               "--The maximum humidity."],
[72 ,       'max_temp',                         'float',                               "--The maximum temperature in temperature_unit."],
[73 ,       'min_humidity',                     'float',                               "--The minimum humidity."],
[74 ,       'min_temp',                         'float',                               "--The minimum temperature in temperature_unit."],
[75 ,       'precision',                        'float',                               "--The precision of the temperature in the system. Defaults to tenths for TEMP_CELSIUS, whole number otherwise."],
[76 ,       'humidity',                         'float',                               "--The target humidity the device is trying to reach."],
[77 ,       'temperature',                      'float',                               "--The temperature currently set to be reached."],
[78 ,       'target_temp_high',                 'float',                               "--The upper bound target temperature."],
[79 ,       'target_temp_low',                  'float',                               "--The lower bound target temperature"],
[80 ,       'target_temp_step',                 'int',                                 "--The supported step size a target temperature can be increased or decreased"],
[81 ,       'temperature_unit',                 'string',                              "--The unit of temperature measurement for the system (TEMP_CELSIUS or TEMP_FAHRENHEIT)."],
[82 ,       'hvac_action',                      'preheating',                          "--Device is preheating."],
[83 ,       'hvac_action',                      'heating',                             "--Device is heating."],
[84 ,       'hvac_action',                      'cooling',                             "--Device is cooling."],
[85 ,       'hvac_action',                      'drying',                              "--Device is drying."],
[86 ,       'hvac_action',                      'fan',                                 "--Device has fan on."],
[87 ,       'hvac_action',                      'defrosting',                          "--Device is defrosting."],
[88 ,       'hvac_action',                      'off',                                 "--Device is off."],
[89 ,       'hvac_action',                      'idle',                                "--Device is doing nothing."],
[90 ,       'fan_mode',                         'on',                                  "--The fan on."],
[91 ,       'fan_mode',                         'off',                                 "--The fan off."],
[92 ,       'fan_mode',                         'auto_high',                           "--The fan turns on automatically high."],
[93 ,       'fan_mode',                         'auto_low',                            "--The fan turns on automatically low."],
[94 ,       'fan_mode',                         'on_low',                              "--The fan speed is low."],
[95 ,       'fan_mode',                         'on_medium',                           "--The fan speed is medium."],
[96 ,       'fan_mode',                         'on_high',                             "--The fan speed is high."],
[97 ,       'fan_mode',                         'middle',                              "--The fan stayes in the middle."],
[98 ,       'fan_mode',                         'focus',                               "--The fan focuses in on direction."],
[99 ,       'fan_mode',                         'diffuse',                             "--The fan diffuse in all possible directions."],
[100,       'swing_mode',                       'off',                                 "--The fan don't swing."],
[101,       'swing_mode',                       'auto',                                "--The fan swings automatically."],
[102,       'swing_mode',                       '1',                                   "--The fan swings with speed 1."],
[103,       'swing_mode',                       '2',                                   "--The fan swings with speed 2."],
[104,       'swing_mode',                       '3',                                   "--The fan swings with speed 3."],
[105,       'swing_mode',                       'vertical',                            "--The fan swings vertically."],
[106,       'swing_mode',                       'horizontal',                          "--The fan swings horizontally."],
[107,       'swing_mode',                       'both',                                "--The fan swings in both directions."],
[108,       'main',                             'string',                              "--Date of the last call in the converstation."],
[109,       'command',                          'string',                              "--The command to trigger the event"],
[110,       'main',                             'closed',                              "--The cover has reach the closed position."],
[111,       'main',                             'closing',                             "--The cover is in the process of closing to reach a set position."],
[112,       'main',                             'open',                                "--The cover has reached the open position."],
[113,       'main',                             'opening',                             "--The cover is in the process of opening to reach a set position."],
[114,       'device_class',                     'awning',                              "--The device class of the binary sensor."],
[115,       'device_class',                     'blind',                               "--The device class of the binary sensor."],
[116,       'device_class',                     'curtain',                             "--The device class of the binary sensor."],
[117,       'device_class',                     'damper',                              "--The device class of the binary sensor."],
[118,       'device_class',                     'garage',                              "--The device class of the binary sensor."],
[119,       'device_class',                     'gate',                                "--The device class of the binary sensor."],
[120,       'device_class',                     'shade',                               "--The device class of the binary sensor."],
[121,       'device_class',                     'sutter',                              "--The device class of the binary sensor."],
[122,       'main',                             'home',                                "--The device is home."],
[123,       'main',                             'not_home',                            "--The cover is not home."],
[124,       'source_type',                      'gps',                                 "--The source of the device connection."],
[125,       'source_type',                      'router',                              "--The source of the device connection."],
[126,       'source_type',                      'bluetooth',                           "--The source of the device connection."],
[127,       'source_type',                      'bluetooth_le',                        "--The source of the device connection."],
[128,       'longitude',                        'float',                               "--The source of the device connection."],
[129,       'latitude',                         'float',                               "--The source of the device connection."],
[130,       'location_accuracy',                'string',                              "--The source of the device connection."],
[131,       'battery',                          'int',                                 "--The source of the device connection."],
[132,       'event_type',                       'pressed',                             "--The event of a button press."],
[133,       'event_type',                       'call_service',                        "--The event of a service called."],
[134,       'event_type',                       'component_loaded',                    "--The event of component loaded."],
[135,       'event_type',                       'core_config_updated',                 "--The event of update the core config."],
[136,       'event_type',                       'data_entry_flow_progressed',          "--The event of data entry flow progresses."],
[137,       'event_type',                       'homeassistant_start',                 "--The event of home assistant starting."],
[138,       'event_type',                       'homeassistant_started',               "--The event ofhome assistant started."],
[139,       'event_type',                       'homeassistant_stop',                  "--The event home assistant stopped."],
[140,       'event_type',                       'homeassistant_final_write',           "--The event home assistant makes it final write befor shutting down."],
[141,       'event_type',                       'logbook_entry',                       "--The event of making a logbook entry."],
[142,       'event_type',                       'service_registered',                  "--The event of register a new service."],
[143,       'event_type',                       'service_removed',                     "--The event of removing a service."],
[144,       'event_type',                       'state_changed',                       "--The event of state change of an entity."],
[145,       'event_type',                       'themes_updated',                      "--The event of the theme change in the ui."],
[146,       'event_type',                       'user_added',                          "--The event for a new user."],
[147,       'event_type',                       'user_removed',                        "--The event to remove a user."],
[148,       'event_type',                       'automation_reloaded',                 "--The event of reloading the automation.yaml files."],
[149,       'event_type',                       'automation_triggered',                "--The event of triggering an automation."],
[150,       'event_type',                       'scene_reloaded',                      "--The event of reload a scene. "],
[151,       'event_type',                       'script_started',                      "--The event of the start of a script."],
[152,       'event_type',                       'area_registry_updated',               "--The event of an area update."],
[153,       'event_type',                       'category_registry_updated',           "--The event of a category registry update."],
[154,       'event_type',                       'device_registry_updated',             "--The event of a device registry update."],
[155,       'event_type',                       'entity_registry_updated',             "--The event of a entity registry update."],
[156,       'event_type',                       'string',                              "--A custom event."],
[157,       'event_data',                       'dict',                                "--List of additional event data"],
[158,       'context',                          'dict',                                "--List of additional event context"],
[159,       'percentage',                       'int',                                 "--The current speed percentage. Must be a value between 0 (off and 100)."],
[160,       'percentage_step',                  'int',                                 "--The steps for the speed percentage. Must be a value between 1 and 100."],
[161,       'oscillating',                      'bool',                                "--The if the fan is oscillating."],
[162,       'direction',                        'forward',                             "--The fan spinns forward."],
[163,       'direction',                        'reverse',                             "--The fan spinns reverse."],
[164,       'action',                           'off',                                 "--The humidifier is off."],
[165,       'action',                           'idle',                                "--The humidifier does nothing."],
[166,       'action',                           'humidifying',                         "--The humidifier humidifying the air."],
[167,       'action',                           'drying',                              "--The humidifier drying the air."],
[168,       'device_class',                     'humidifier',                          "--The humidifier is a humidifier."],
[169,       'device_class',                     'dehumidifier',                        "--The humidifier is a dehumidifier."],
[170,       'main',                             'mowing', 	                            "--The lawn mower is currently mowing."],
[171,       'main',                             'docked',	                            "--The lawn mower is done mowing and is currently docked."],
[172,       'main',                             'paused',	                            "--The lawn mower was active and is now paused."],
[173,       'main',                             'error',                               "--The lawn mower encountered an error while active and needs assistance."],
[174,       'effect',                           'rainbow',                             "--The light makes a rainbow effect."],
[175,       'effect',                           'none',                                "--The light makes no effect."],
[176,       'min_color_temp_kelvin',            'int',                                 "--The minimal color value."],
[177,       'max_color_temp_kelvin',            'int',                                 "--The maximal color value."],
[178,       'color_mode',                       'color_temp',                          "--The ui color setting."],
[179,       'color_mode',                       'hs',                                  "--The ui color setting."],
[180,       'brightness',                       'int',                                 "--The brightness of the light."],
[181,       'color_temp_kelvin',                'int',                                 "--The color of the light as kelvin number."],
[182,       'hs_color',                         'tuple[float, float]',                 "--The color of the light in hs-format."],
[183,       'rgb_color',                        'tuple[int, int, int]',                "--The color of the light in rgb-format."],
[184,       'xy_color',                         'tuple[float, float]',                 "--The color of the light in xy-format."],
[185,       'rgbw_color',                       'tuple[int, int, int, int]',           "--The color of the light in rgbw-format."],
[186,       'rgbww_color',                      'tuple[int, int, int, int, int]',      "--The color of the light in rgbww-format."],
[187,       'main',                             'jammed',                              "--The lock is unabled to toggle."],
[188,       'main',                             'locked',                              "--The lock is locked."],
[189,       'main',                             'locking',                             "--The lock is looking."],
[190,       'main',                             'unlocked',                            "--The lock is unlocked."],
[191,       'main',                             'unlocking',                           "--The lock is unlooking."],
[192,       'main',                             'playing',                             "--The media player playimg something."],
[193,       'main',                             'standby',                             "--The media player is in standby mode."],
[194,       'main',                             'buffering',                           "--The media player buffering something."],
[195,       'volume_level',                     'float',                               "--The volume level of the media player in the range (0..1)."],
[196,       'is_volume_muted',                  'bool',                                "--Its true if volume is currently muted."],
[197,       'volume_step',                      'float',                               "--The volume step to use for the volume_up and volume_down services."],
[198,       'media_content_id',                 'string',                              "--The content ID of current playing media."],
[199,       'media_content_type',               'album',                               "--The content type of current playing media."],
[200,       'media_content_type',               'app',                                 "--The content type of current playing media."],
[201,       'media_content_type',               'artist',                              "--The content type of current playing media."],
[202,       'media_content_type',               'channel',                             "--The content type of current playing media."],
[203,       'media_content_type',               'channels',                            "--The content type of current playing media."],
[204,       'media_content_type',               'composer',                            "--The content type of current playing media."],
[205,       'media_content_type',               'contibuting_artist',                  "--The content type of current playing media."],
[206,       'media_content_type',               'episode',                             "--The content type of current playing media."],
[207,       'media_content_type',               'game',                                "--The content type of current playing media."],
[208,       'media_content_type',               'genre',                               "--The content type of current playing media."],
[209,       'media_content_type',               'image',                               "--The content type of current playing media."],
[210,       'media_content_type',               'movie',                               "--The content type of current playing media."],
[211,       'media_content_type',               'music',                               "--The content type of current playing media."],
[212,       'media_content_type',               'playlist',                            "--The content type of current playing media."],
[213,       'media_content_type',               'podcast',                             "--The content type of current playing media."],
[214,       'media_content_type',               'season',                              "--The content type of current playing media."],
[215,       'media_content_type',               'track',                               "--The content type of current playing media."],
[216,       'media_content_type',               'tvshow',                              "--The content type of current playing media."],
[217,       'media_content_type',               'url',                                 "--The content type of current playing media."],
[218,       'media_content_type',               'video',                               "--The content type of current playing media."],
[219,       'app_name',                         'string',                              "--The name of the current running app."],
[220,       'group_members',                    'list[string]',                        "--A dynamic list of player entities which are currently grouped together for synchronous playback."],
[221,       'media_album_artist',               'string',                              "--The album artist of current playing media, music track only."],
[222,       'media_album_name',                 'string',                              "--The album name of current playing media, music track only."],
[223,       'media_artist',                     'string',                              "--The artist of current playing media, music track only."],
[224,       'media_channel',                    'string',                              "--The channel currently playing."],
[225,       'media_duration',                   'int',                                 "--The duration of current playing media in seconds."],
[226,       'media_episode',                    'string',                              "--The episode of current playing media, TV show only."],
[227,       'media_playlist',                   'string',                              "--The duration of current playing media in seconds."],
[228,       'media_position',                   'int',                                 "--The episode of current playing media, TV show only"],
[229,       'media_season',                     'string',                              "--The duration of current playing media in seconds."],
[230,       'media_series_title',               'string',                              "--The episode of current playing media, TV show only"],
[231,       'media_title',                      'string',                              "--The duration of current playing media in seconds."],
[232,       'media_track',                      'int',                                 "--The track number of current playing media, music track only."],
[233,       'repeat',                           'off',                                 "--The current repeat mode."],
[234,       'repeat',                           'one',                                 "--The current repeat mode."],
[235,       'repeat',                           'all',                                 "--The current repeat mode."],
[236,       'shuffle',                          'bool',                                "--True if shuffle is enabled."],
[237,       'source',                           'dvd',                                 "--The currently selected input source for the media player."],
[238,       'source',                           'youtube',                             "--The currently selected input source for the media player."],
[239,       'sound_mode',                       'music',                               "--The current sound mode of the media player."],
[240,       'sound_mode',                       'movie',                               "--The current sound mode of the media player."],
[241,       'device_class',                     'tv',                                  "--The media player is a tv."],
[242,       'device_class',                     'speaker',                             "--The media player is a speaker."],
[243,       'device_class',                     'receiver',                            "--The media player is a receiver."],
[244,       'main',                             'float',                               "--The number of the entity."],
[245,       'min',                              'float',                               "--The minimum accepted value in the number's (inclusive)."],
[246,       'max',                              'float',                               "--The maximum accepted value in the number's (inclusive)."],
[247,       'step',                             'float',                               "--Defines the resolution of the values, i.e. the smallest increment or decrement in the number's."],
[248,       'mode',                             'string',                              "--Defines how the number should be displayed in the UI. Can be box, slider or auto."],
[249,       'activity',                         'string',                              "--The minimum accepted value in the number's (inclusive)."],
[250,       'current_activity',                 'string',                              "--The maximum accepted value in the number's (inclusive)."],
[251,       'id',                               'string',                              "--The id of the scene."],
[252,       'entity_id',                        'string',                              "--The id of the entity in the scene."],
[253,       'main', 	                        'option',                              "--The one of the options of the select."],
[254,       'options',                          'list[string]',                        "--All options of the select."],
[255,       'device_class',                     'apparent_power',                      "--The device class of the sensor."],
[256,       'device_class',                     'aqi',                                 "--The device class of the sensor."],
[257,       'device_class',                     'atmospheric_pressure',                "--The device class of the sensor."],
[258,       'device_class',                     'conductivity',                        "--The device class of the sensor."],
[259,       'device_class',                     'carbon_dioxide',                      "--The device class of the sensor."],
[260,       'device_class',                     'carbon_monoxide',                     "--The device class of the sensor."],
[261,       'device_class',                     'current',                             "--The device class of the sensor."],
[262,       'device_class',                     'data_rate',                           "--The device class of the sensor."],
[263,       'device_class',                     'data_size',                           "--The device class of the sensor."],
[264,       'device_class',                     'distance',                            "--The device class of the sensor."],
[265,       'device_class',                     'duration',                            "--The device class of the sensor."],
[266,       'device_class',                     'energy',                              "--The device class of the sensor."],
[267,       'device_class',                     'energy_storage',                      "--The device class of the sensor."],
[268,       'device_class',                     'frequency',                           "--The device class of the sensor."],
[269,       'device_class',                     'humidity',                            "--The device class of the sensor."],
[270,       'device_class',                     'illuminance',                         "--The device class of the sensor."],
[271,       'device_class',                     'irradiance',                          "--The device class of the sensor."],
[272,       'device_class',                     'monetary',                            "--The device class of the sensor."],
[273,       'device_class',                     'nitrogen_dioxide',                    "--The device class of the sensor."],
[274,       'device_class',                     'nitrogen_monoxide',                   "--The device class of the sensor."],
[275,       'device_class',                     'nitrous_oxide',                       "--The device class of the sensor."],
[276,       'device_class',                     'ozone',                               "--The device class of the sensor."],
[277,       'device_class',                     'ph',                                  "--The device class of the sensor."],
[278,       'device_class',                     'pm1',                                 "--The device class of the sensor."],
[279,       'device_class',                     'pm10',                                "--The device class of the sensor."],
[280,       'device_class',                     'pm25',                                "--The device class of the sensor."],
[281,       'device_class',                     'power_factor',                        "--The device class of the sensor."],
[282,       'device_class',                     'precipitation',                       "--The device class of the sensor."],
[283,       'device_class',                     'precipitation_intensity',             "--The device class of the sensor."],
[284,       'device_class',                     'pressure',                            "--The device class of the sensor."],
[285,       'device_class',                     'reactive_power',                      "--The device class of the sensor."],
[286,       'device_class',                     'signal_strength',                     "--The device class of the sensor."],
[287,       'device_class',                     'sound_pressure',                      "--The device class of the sensor."],
[288,       'device_class',                     'speed',                               "--The device class of the sensor."],
[289,       'device_class',                     'sulphur_dioxide',                     "--The device class of the sensor."],
[290,       'device_class',                     'temperature',                         "--The device class of the sensor."],
[291,       'device_class',                     'volatile_organic_compounds',          "--The device class of the sensor."],
[292,       'device_class',                     'volatile_organic_compounds_parts',    "--The device class of the sensor."],
[293,       'device_class',                     'voltage',                             "--The device class of the sensor."],
[294,       'device_class',                     'volume',                              "--The device class of the sensor."],
[295,       'device_class',                     'volume_storage',                      "--The device class of the sensor."],
[296,       'device_class',                     'volume_flow_rate',                    "--The device class of the sensor."],
[297,       'device_class',                     'water',                               "--The device class of the sensor."],
[298,       'device_class',                     'weight',                              "--The device class of the sensor."],
[299,       'device_class',                     'wind_speed',                          "--The device class of the sensor."],
[300,       'unit_of_measurement',              'string',                              "--The unit of the sensor value."],
[301,       'battery_level',                    'int',                                 "--The battery level of the sensor."],
[302,       'device_class',                     'date',                                "--The device class of the sensor."],
[303,       'device_class',                     'timestamp',                           "--The device class of the sensor."],
[304,       'available_tones',                  'list[string]',                        "--The list of possible sounds for the siren."],
[305,       'device_class',                     'switch',                              "--The device class of the switch."],
[306,       'device_class',                     'outlet',                              "--The device class of the switch."],
[307,       'mode',                             'text',                                "--The text ui mode."],
[308,       'mode',                             'password',                            "--The text ui mode."],
[309,       'pattern',                          'string',                              "--A regex pattern that the text value must match to be valid."],
[310,       'main',                             'int',                                 "--A TodoListEntity state is the count of incomplete items in the To-do list."],
[311,       'auto_update',                      'bool',                                "--The device or service that the entity represents has auto update logic. When this is set to True you can not skip updates."],
[312,       'installed_version',                'string',                              "--The currently installed and used version of the software."],
[313,       'in_progress',                      'int',                                 "--Update installation progress. Can either return a boolean (1 if in progress, 0 if not or an int to indicate the progress from 0 to 100%)."],
[314,       'release_summary',                  'string',                              "--Summary of the release notes or changelog."],
[315,       'release_url',                      'string',                              "--URL to the full release notes of the latest version available."],
[316,       'current_version',                  'string',                              "--The current version of the update."],
[317,       'skipped_version',                  'string',                              "--The version that was skipped."],
[318,       'title',                            'string',                              "--Title of the software."],
[319,       'latest_version',                   'string',                              "--The latest version of the software available."],
[320,       'device_class',                     'firmware',                            "--The device class of the update."],
[321,       'main',                             'cleaning',                            "--The vacuum is cleaning."],
[322,       'main',                             'returning',                           "--The vacuum is returning to the dock."],
[323,       'battery_icon',                     'string',                              "--The time the vacuum has been cleaning."],
[324,       'cleaned_area',                     'float',                               "--The percentage of the area that has been cleaned."],
[325,       'fan_speed',                        'min',                                 "--The speed of the vacuum fan."],
[326,       'fan_speed',                        'medium',                              "--The speed of the vacuum fan."],
[327,       'fan_speed',                        'high',                                "--The speed of the vacuum fan."],
[328,       'fan_speed',                        'max',                                 "--The speed of the vacuum fan."],
[329,       'current_position',                 'int',                                  "--The current position of the valve."],
[330,       'main',                             'eco',                                 "--The water heater is in eco mode."],
[331,       'main',                             'electric',                            "--The water heater is in electric mode."],
[332,       'main',                             'performance',                         "--The water heater is in high performance mode."],
[333,       'main',                             'high_demand',                         "--The water heater is in high performance mode."],
[334,       'main',                             'heat_pump',                           "--The water heater is in heat pump mode."],
[335,       'main',                             'gas',                                 "--The water heater is in gas mode."],
[336,       'operation_mode',                   'eco',                                 "--The operation mode of the water heater."],
[337,       'operation_mode',                   'electric',                            "--The operation mode of the water heater."],
[338,       'operation_mode',                   'performance',                         "--The operation mode of the water heater."],
[339,       'operation_mode',                   'high_demand',                         "--The operation mode of the water heater."],
[340,       'operation_mode',                   'heat_pump',                           "--The operation mode of the water heater."],
[341,       'operation_mode',                   'gas',                                 "--The operation mode of the water heater."],
[342,       'operation_mode',                   'off',                                 "--The operation mode of the water heater."],
[343,       'away_mode',                        'on',                                  "--The away mode of the water heater."],
[344,       'away_mode',                        'off',                                 "--The away mode of the water heater."],
[345,       'main',                             'clear-night',                         "--The weather is clear at night."],
[346,       'main',                             'cloudy',                              "--The weather is cloudy."],
[347,       'main',                             'exceptional',                         "--The weather is exceptional."],
[348,       'main',                             'fog',                                 "--The weather is foggy."],
[349,       'main',                             'hail',                                "--The weather is hailing."],
[350,       'main',                             'lightning',                           "--The weather is lightning."],
[351,       'main',                             'lightning-rainy',                     "--The weather is lightning and rainy."],
[352,       'main',                             'partlycloudy',                        "--The weather is partly cloudy."],
[353,       'main',                             'pouring',                             "--The weather is pouring."],
[354,       'main',                             'rainy',                               "--The weather is rainy."],
[355,       'main',                             'snowy',                               "--The weather is snowy."],
[356,       'main',                             'snowy-rainy',                         "--The weather is snowy and rainy."],
[357,       'main',                             'sunny',                               "--The weather is sunny."],
[358,       'main',                             'windy',                               "--The weather is windy."],
[359,       'main',                             'windy-variant',                       "--The weather is windy and variant."],
[360,       'attribution',                      'string',                              "--The attributor of the weather."],
[361,       'apparent_temperature',             'float',                               "--The current apparent (feels-like temperature in °C or °F)."],
[362,       'pressure',                         'flaot',                               "--The pressure of the weather."],
[363,       'pressure_unit',                    'string',                              "--The pressure unit of the weather."],
[364,       'wind_speed',                       'float',                               "--The wind bearing of the weather."],
[365,       'wind_speed_unit',                  'string',                              "--The wind speed unit of the weather."],
[366,       'wind_bearing',                     'string',                              "--The current wind bearing in azimuth angle (degrees or 1-3 letter cardinal direction)."],
[367,       'wind_gust_speed',                  'float',                               "--he current wind gust speed."],
[368,       'visibility',                       'float',                               "--The visibility of the weather."],
[369,       'visibility_unit',                  'string',                              "--The visibility unit of the weather."],
[370,       'cloud_coverage',                   'int',                                 "--The cloud coverage of the weather."],
[371,       'dew_point',                        'float',                               "--The dew point temperature in °C or °F."],
[372,       'ozone',                            'float',                               "--The current ozone level of the weather."],
[373,       'uv_index',                         'float',                               "--The uv index of the weather."],
[374,       'precipitation_unit',               'string',                              "-- The precipitation unit in mm or in."],
]


old_integration_values = [
[1, 1],
[1, 2],
[1, 3],
[1, 4],
[1, 5],
[1, 6],
[1, 7],
[1, 8],
[1, 9],
[1, 10],
[1, 11],
[1, 12],
[1, 13],
[1, 70],
[1, 71],
[1, 72],
[1, 73],
[1, 74],
[2, 12],
[2, 13],
[2, 14],
[2, 15],
[2, 75],
[2, 76],
[2, 77],
[2, 78],
[2, 79],
[2, 80],
[2, 81],
[2, 82],
[2, 83],
[2, 84],
[2, 85],
[2, 86],
[2, 87],
[2, 88],
[2, 89],
[2, 90],
[2, 91],
[2, 92],
[2, 93],
[2, 94],
[2, 95],
[2, 96],
[2, 97],
[2, 98],
[2, 99],
[2, 100],
[2, 101],
[2, 102],
[3, 12],
[3, 13],
[4, 12],
[4, 13],
[4, 14],
[4, 15],
[4, 103],
[4, 104],
[4, 105],
[4, 106],
[4, 107],
[4, 108],
[5, 12],
[5, 13],
[5, 16],
[5, 17],
[5, 18],
[5, 109],
[5, 110],
[5, 74], 
[6, 12], 
[6, 13], 
[6, 15], 
[6, 19],
[6, 20],
[6, 21],
[6, 22],
[6, 23],
[6, 24],
[6, 111],
[6, 112],
[6, 113],
[6, 114],
[6, 115],
[6, 116],
[6, 117],
[6, 118],
[6, 119],
[6, 120],
[6, 121],
[6, 122],
[6, 123],
[6, 124],
[6, 125],
[6, 126],
[6, 127],
[6, 128],
[6, 129],
[6, 130],
[6, 131],
[6, 132],
[6, 133],
[6, 134],
[6, 135],
[6, 136],
[6, 137],
[6, 138],
[6, 139],
[6, 140],
[6, 141],
[6, 142],
[6, 143],
[6, 144],
[6, 145],
[6, 146],
[6, 147],
[6, 148],
[6, 149],
[6, 74], 
[7, 12],
[7, 13],
[7, 25],
[8, 12],
[8, 13],
[8, 26],
[8, 27],
[8, 28],
[8, 29],
[8, 150],
[8, 151],
[8, 152],
[8, 153],
[8, 154],
[8, 155],
[8, 156],
[8, 157],
[8, 80], 
[8, 102],
[8, 74], 
[9, 12],
[9, 13],
[9, 25],
[10, 12],
[10, 13],
[10, 25],
[11, 12],
[11, 13],
[11, 30],
[11, 31],
[11, 158],
[11, 159],
[11, 160],
[11, 161],
[11, 162],
[11, 163],
[11, 164],
[11, 165],
[12, 12],
[12, 13],
[12, 25],
[12, 166],
[12, 167],
[12, 168],
[12, 169],
[12, 170],
[12, 171],
[12, 172],
[12, 173],
[12, 174],
[12, 175],
[12, 176],
[12, 177],
[12, 178],
[12, 179],
[12, 180],
[12, 181],
[12, 182],
[12, 183],
[12, 184],
[12, 185],
[12, 186],
[12, 187],
[12, 188],
[12, 189],
[12, 190],
[13, 12],
[13, 13],
[13, 14],
[13, 15],
[13, 191],
[13, 192],
[13, 193],
[13, 194],
[13, 195],
[13, 74],
[14, 12],
[14, 13],
[14, 14],
[14, 15],
[14, 115],
[14, 113],
[14, 111],
[14, 118],
[14, 196],
[14, 197],
[14, 198],
[14, 199],
[14, 200],
[14, 201],
[14, 74],
[15, 12],
[15, 13],
[15, 25],
[16, 12],
[16, 13],
[16, 32],
[16, 33],
[16, 34],
[16, 35],
[17, 12],
[17, 13],
[17, 14],
[17, 15],
[17, 202],
[17, 203],
[17, 204],
[17, 205],
[17, 206],
[17, 207],
[17, 208],
[17, 209],
[17, 210],
[17, 211],
[17, 212],
[17, 213],
[17, 214],
[17, 74],
[18, 12],
[18, 13],
[18, 28],
[18, 29],
[18, 36],
[18, 37],
[18, 38],
[18, 39],
[18, 40],
[18, 70],
[18, 71],
[18, 72],
[18, 74],
[19, 12],
[19, 13],
[19, 14],
[19, 15],
[19, 16],
[19, 34],
[19, 41],
[19, 42],
[19, 43],
[19, 215],
[19, 216],
[19, 217],
[19, 218],
[19, 219],
[19, 220],
[19, 221],
[19, 222],
[19, 223],
[19, 224],
[19, 225],
[19, 226],
[19, 227],
[19, 228],
[19, 229],
[19, 230],
[19, 231],
[19, 232],
[19, 233],
[19, 234],
[19, 235],
[19, 236],
[19, 237],
[19, 238],
[19, 239],
[19, 240],
[19, 241],
[19, 242],
[19, 243],
[19, 244],
[19, 245],
[19, 246],
[19, 247],
[19, 248],
[19, 249],
[19, 250],
[19, 251],
[19, 252],
[19, 253],
[19, 254],
[19, 255],
[19, 256],
[19, 257],
[19, 258],
[19, 259],
[19, 260],
[19, 261],
[19, 262],
[19, 263],
[19, 74],
[20, 12],
[20, 13],
[20, 74],
[21, 12],
[21, 13],
[21, 44],
[21, 264],
[21, 265],
[21, 266],
[21, 267],
[22, 12],
[22, 13],
[22, 25],
[22, 268],
[22, 269],
[23, 12],
[23, 13],
[23, 25],
[23, 270],
[23, 271],
[24, 12],
[24, 13],
[24, 45],
[24, 272],
[25, 12],
[25, 13],
[25, 44],
[25, 273],
[25, 274],
[25, 275],
[25, 276],
[25, 277],
[25, 278],
[25, 279],
[25, 280],
[25, 281],
[25, 282],
[25, 283],
[25, 284],
[25, 285],
[25, 286],
[25, 287],
[25, 288],
[25, 289],
[25, 290],
[25, 291],
[25, 292],
[25, 293],
[25, 294],
[25, 295],
[25, 296],
[25, 297],
[25, 298],
[25, 299],
[25, 300],
[25, 301],
[25, 302],
[25, 303],
[25, 304],
[25, 305],
[25, 306],
[25, 307],
[25, 308],
[25, 309],
[25, 310],
[25, 311],
[25, 312],
[25, 313],
[25, 314],
[25, 315],
[25, 316],
[25, 317],
[25, 318],
[25, 319],
[25, 75],
[25, 82],
[25, 86],
[25, 92],
[26, 12],
[26, 13],
[26, 25],
[26, 320],
[26, 321],
[27, 12],
[27, 13],
[27, 45],
[28, 12],
[28, 13],
[28, 14],
[28, 15],
[28, 322],
[28, 74],
[29, 12],
[29, 13],
[30, 12],
[30, 13],
[30, 14],
[30, 15],
[30, 323],
[30, 324],
[31, 12],
[31, 13],
[31, 25],
[31, 325],
[31, 326],
[31, 327],
[31, 264],
[31, 265],
[32, 12],
[32, 13],
[32, 25],
[33, 12], 
[33, 13], 
[33, 46],
[33, 74], 
[34, 12], 
[34, 13], 
[35, 12], 
[35, 13], 
[35, 14], 
[35, 15], 
[35, 328],
[35, 329],
[35, 330],
[35, 331],
[35, 332],
[35, 333],
[35, 334],
[35, 335],
[35, 336],
[35, 337],
[35, 74], 
[36, 12], 
[36, 13], 
[36, 16], 
[36, 33], 
[36, 34], 
[36, 35], 
[36, 47],
[36, 48],
[36, 319],
[36, 338],
[36, 339],
[36, 340],
[36, 341],
[36, 342],
[36, 343],
[36, 74], 
[37, 12], 
[37, 13], 
[37, 26], 
[37, 27], 
[37, 28], 
[37, 29], 
[37, 82], 
[37, 315],
[37, 344],
[38, 12], 
[38, 13], 
[38, 25], 
[39, 12], 
[39, 13], 
[39, 15], 
[39, 21], 
[39, 49],
[39, 50],
[39, 51],
[39, 52],
[39, 53],
[39, 54],
[39, 116],
[39, 114],
[39, 112],
[39, 119],
[39, 120],
[39, 121],
[39, 345],
[39, 346],
[39, 347],
[39, 348],
[39, 349],
[39, 350],
[39, 351],
[39, 352],
[39, 353],
[39, 74], 
[40, 12], 
[40, 13], 
[40, 15], 
[40, 21], 
[40, 55],
[40, 56],
[40, 57],
[40, 58],
[40, 59],
[40, 60],
[40, 61],
[40, 62],
[40, 63],
[40, 64],
[40, 65],
[40, 66],
[40, 67],
[40, 68],
[40, 69],
[40, 118],
[40, 119],
[40, 123],
[40, 354],
[40, 355],
[40, 356],
[40, 357],
[40, 358],
[40, 359],
[40, 360],
[40, 361],
[40, 362],
[40, 363],
[40, 364],
[40, 365],
[40, 366],
[40, 367],
[40, 368],
[40, 74]
]

integrations = [
'alarm_control_panel',
'binary_sensor',
'button',
'calendar',
'camera',
'climate',
'conversation',
'cover',
'date',
'datetime',
'device_tracker',
'event',
'fan',
'humidifier',
'image',
'lawn_mower',
'light',
'lock',
'media_player',
'notify',
'number',
'remote',
'scene',
'select',
'sensor_float',
'sensor_string',
'sensor_enum',
'siren',
'stt',
'switch',
'text',
'time',
'todo',
'tts',
'update',
'vacuum',
'valve',
'wake_word',
'water_heater',
'weather'
'homeassistant',
'mqtt',
'sun',
'tag',
'time_pattern',
'persistent_notification',
'webhook',
'zone',
'device',
]

def get_matching_entries(old_list, new_list):
    matching_entries = {}
    found_match = False
    for old_entry in old_list:
        for new_entry in new_list:
            if old_entry[1] == "main" and new_entry[1] == "main" and old_entry[2] == new_entry[2]:
                matching_entries[old_entry[0]] = new_entry[0]
                found_match = True
            elif not old_entry[1] == "main" and old_entry[1] == new_entry[1] and old_entry[2] == new_entry[2]:
                matching_entries[old_entry[0]] = new_entry[0] 
                found_match = True
        if not found_match:
            print(f'No match found for {old_entry[0]} {old_entry[1]} {old_entry[2]}')
        found_match = False
    return matching_entries

def get_new_values(old_list, new_list):
    matching_dict= get_matching_entries(old_list, new_list)
    for new_entry in new_list:
        if matching_dict.values() == new_entry[0]:
            print(f'No match found for {new_entry[0]} {new_entry[1]} {new_entry[2]}')

def check_for_duplicates(old_list, new_list):
    matching_dict= get_matching_entries(old_list, new_list)
    matching_values = set()
    for value in matching_dict.values():
        if value in matching_values:
            print(f"Duplicate value found: {value}")
        matching_values.add(value)

def make_new_list_comment_dict(new_list):
    new_list_comment_dict = {}
    for entry in new_list:
        new_list_comment_dict[entry[0]] = entry[3]
    return new_list_comment_dict


def write_new_integration_value_file(old_list, new_list, old_integration_values):
    with open('schema/new_integration_vals.txt', 'w', encoding='utf8') as file:
        matching_dict= get_matching_entries(old_list, new_list)
        new_list_comment_dict = make_new_list_comment_dict(new_list)
        file.write(f'--{integrations[0]}\n')
        integration_num = 1
        for entry in old_integration_values:
            if integration_num != entry[0]:
                file.write(f'--{integrations[integration_num]}\n')
                integration_num += 1
            new_number = matching_dict[entry[1]]
            file.write(f'({entry[0]}, \t {new_number}), \t \t {new_list_comment_dict[new_number]}\n')
    
def check_missing_new_ids(new_list, old_integration_values):
    matching_dict= get_matching_entries(old_list, new_list)
    remaining_nums = set(range(1, len(new_list) + 1))
    for entry in old_integration_values:
        new_number = matching_dict[entry[1]]
        if new_number in remaining_nums:
            remaining_nums.remove(new_number)
    print(remaining_nums)



if __name__ == '__main__':
    # get_new_integration_values(old_list, new_list, old_integration_values)
    check_missing_new_ids(new_list, old_integration_values)

