"""
WARNING: This file was generated by the automation_script_gen module.
         Changes to this file may alter the automation flow or prevent the repeatability of a test run.

Please only change this file if you know what you are doing.
"""

import sys
import json

# read the arguments
serialized_entities = sys.argv[1]

entities_list = json.loads(serialized_entities)
