alias: all triggers
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.bedroom
    enabled: true
  - platform: event
    event_type: test
    event_data:
      test: tst1
  - platform: numeric_state
    entity_id:
      - sensor.carbon_monoxide
    above: 10
    below: 50000
  - platform: persistent_notification
    update_type:
      - added
      - removed
    notification_id: test_id
  - platform: numeric_state
    entity_id:
      - sensor.light_living_room
    for:
      hours: 0
      minutes: 10
      seconds: 0
    above: 2
    below: 4000
  - platform: mqtt
    topic: topic/topic
    payload: test_payload
    qos: 1
  - platform: zone
    entity_id: person.admin
    zone: zone.home
    event: enter
  - platform: calendar
    event: start
    entity_id: calendar.calendar_1
    offset: "0:5:0"
  - platform: template
    value_template: "True"
    for:
      hours: 3
      minutes: 0
      seconds: 0
      milliseconds: 0
  - platform: zone
    entity_id: device_tracker.demo_anne_therese
    zone: zone.home
    event: enter
  - platform: state
    entity_id:
      - sensor.carbon_dioxide
      - sensor.outside_humidity
    attribute: battery_level
condition: []
action: []
mode: single
