alias: verzweigung
description: ""
trigger:
  - platform: state
    entity_id:
      - humidifier.humidifier
condition:
  - condition: not
    conditions:
      - condition: and
        conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: vacuum.0_ground_floor
                state: unavailable
              - condition: state
                entity_id: vacuum.0_ground_floor
                state: unavailable
          - condition: state
            entity_id: vacuum.0_ground_floor
            state: unavailable
      - condition: numeric_state
        entity_id: sensor.carbon_dioxide
        above: 10
action:
  - type: turn_on
    device_id: 7f6e169dcdf4b5ef7904aeff83333410
    entity_id: c6ff22d2817f164c951419c23a07a12b
    domain: switch
mode: single