alias: Wohnzimmerlampe einschalten
description: ""
trigger:
  - alias: Wenn eine Bewegung erkannt wird
    platform: state
    entity_id:
      - binary_sensor.moving_living_room
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.person_living_room
    from: "off"
    to: "on"
    alias: Wenn eine Person erkannt wird
condition:
  - alias: Ist die Sonne untergegangen
    condition: sun
    after: sunrise
  - condition: state
    entity_id: light.main_light_living_room
    state: "on"
    alias: Ist das Deckenlicht angeschaltet
action:
  - alias: Deckenlicht einschalten
    service: light.turn_on
    data: {}
    target:
      entity_id: light.ceiling_lights
  - choose:
      - conditions:
          - alias: Ist Person Krista im Wohnzimmer
            condition: state
            entity_id: sensor.whos_in_living_room
            state: Krista
          - condition: not
            conditions:
              - condition: state
                entity_id: media_player.living_room
                state: playing
        sequence:
          - alias: Musikanlage einschalten
            service: media_player.media_play
            target:
              entity_id: media_player.living_room
            data: {}
mode: single
