alias: Deckenlicht mit Schalter ausschalten
description: >-
  Die anderen Aktionen beim Ausschalten der Deckenlampe werden auf das
  Ausschalten per Schalter übertragen.
trigger:
  - platform: state
    entity_id:
      - switch.main_light_living_room
    to: null
condition:
  - condition: state
    entity_id: light.main_light_living_room
    state: "off"
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: media_player.living_room
            state: playing
        sequence:
          - service: media_player.media_pause
            metadata: {}
            data: {}
  - service: automation.turn_off
    metadata: {}
    data:
      stop_actions: true
    target:
      entity_id: automation.turn_on_living_room_main_light
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: automation.turn_on
    target:
      entity_id: automation.turn_on_living_room_main_light
    data: {}
mode: single
