trigger:
  - platform: state
    entity_id:
      - binary_sensor.moving_living_room
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.person_living_room
    to: "on"
action:
  - service: input_boolean.turn_on
    data: {}
  - condition: state
    entity_id: sensor.whos_in_living_room
    state: Krista
  - service: media_player.media_play
    target:
      entity_id: media_player.living_room
    data: {}