"""
WARNING: This file was generated by the automation_script_gen module.
		 Changes to this file may alter the automation flow or prevent the repeatability of a test run.

Please only change this file if you know what you are doing.
"""

import sys
import json

# read the arguments
serialized_inputs = sys.argv[1]

input_vals = json.loads(serialized_inputs)

trigger_id: str = None


def trigger_check(input_vals) -> bool:
	triggered = False
	trigger = input_vals[0]
	global trigger_id
	if (trigger[0] is not None and (trigger[0] == "off")):
		trigger_id = None
		triggered = True

	# The end of the trigger section
	return triggered


def action_execution(input_vals) -> None:
	action_inputs = input_vals[2]
	action_results = []
		
	if action_inputs != [] and None in action_inputs:
		return print(json.dumps({"ValueError": "Action input values cannot be None"}))

	action_results.append({'media_player.test_actor':'media_pause'})


	# The end of the action section
	print(json.dumps(action_results))

if __name__ == "__main__":
	if trigger_check(input_vals):
		action_execution(input_vals)
